
POST http://localhost:3000/api/categorias HTTP/1.1
Content-Type: application/json

{
    "id_categoria":"C2",
    "desc_categorias":"productos_variados"
}

###
GET http://localhost:3000/api/categorias HTTP/1.1

###
GET http://localhost:3000/api/categorias/ HTTP/1.1

###
PUT http://localhost:3000/api/categorias/ HTTP/1.1
content-Type: application/json

{
    "id_categoria":"C1",
    "desc_categorias":"Medicamentos"
}

###
DELETE http://localhost:3000/api/categorias/HTTP/1.1
